from . import asset_brand
from . import asset_model
from . import asset_type
from . import it_assets
from . import it_components
from . import res_partner
from . import system_system
from . import it_assignment
from . import hr_employee
